# Generated by Django 4.2 on 2023-04-14 04:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("board", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(name="BoardMember",),
    ]
